-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 18:13:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema anya_social_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anya_social_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anya_social_database` DEFAULT CHARACTER SET utf8 ;
USE `anya_social_database` ;

-- -----------------------------------------------------
-- Table `anya_social_database`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anya_social_database`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anya_social_database`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anya_social_database`.`messages` (
  `msg_id` INT UNSIGNED NOT NULL,
  `msg_text` LONGTEXT NOT NULL,
  `msg_date` BIGINT UNSIGNED NULL,
  `msg_sender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`msg_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anya_social_database`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anya_social_database`.`chats` (
  `chat_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chat_msg_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`chat_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
